# simple BiocCheck worklow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: BiocCheck

jobs:
  BiocCheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::BiocCheck, any::XML

      - name: Run BiocCheck
        run: |
          BiocCheck::BiocCheck(
              dir('check', 'tar.gz$', full.names = TRUE),
              `quit-with-status` = TRUE,
              `no-check-R-ver` = TRUE,
              `no-check-bioc-help` = TRUE
          )
        shell: Rscript {0}

      - name: Upload BiocCheck results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: bioccheck-test-failures
          path: ${{ runner.temp }}/package
